import Head from 'next/head'
import Grainyent from '../components/Grainyent'


export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>Grainyents - Grainy Gradients</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grainyent />
      
    </div>
  )
}
